In [1]:
N_THREADS = 8
# Nota Bene : notebooks don't deallocate GPU memory
IS_FORCE_CPU = True # can also be set in the trainer

In [2]:
%autosave 600
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

# CENTER PLOTS
from IPython.core.display import HTML
display(HTML(""" <style> .output_png {display: table-cell; text-align: center; margin:auto; }
.prompt display:none;}  </style>"""))

import os
if IS_FORCE_CPU:
    os.environ['CUDA_VISIBLE_DEVICES'] = ""

import sys
sys.path.append("notebooks")

import numpy as np
import matplotlib.pyplot as plt
import torch
torch.set_num_threads(N_THREADS)

Autosaving every 600 seconds


In [14]:
tensor = torch.arange(6).view(2,3).float()

In [15]:
tensor

tensor([[0., 1., 2.],
        [3., 4., 5.]])

In [18]:
torch.nn.functional.normalize(tensor, p=1, dim=0)

tensor([[0.0000, 0.2000, 0.2857],
        [1.0000, 0.8000, 0.7143]])

In [20]:
torch.nn.functional.softplus(torch.tensor([-1.]))

tensor([0.3133])

In [21]:
r=torch.nn.Conv1d(2,2,2)

In [23]:
r.in_channels

2